# Generated by Django 3.1.1 on 2020-10-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201013_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
