# Generated by Django 3.1.1 on 2020-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201014_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
