# Generated by Django 3.1.1 on 2020-10-21 15:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201015_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(max_length=200, unique=True, validators=[blog.models.validate_id], verbose_name='ID статьи для посетителями сайта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='markdown_text',
            field=models.TextField(verbose_name='текст в формате markdown'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.TextField(max_length=1024, verbose_name='выдержка из статьи в формате markdown для предварительного просмотра'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(verbose_name='дата и время публикации статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='теги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(max_length=200, unique=True, validators=[blog.models.validate_id], verbose_name='ID тега для посетителей сайта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=200, verbose_name='тег'),
        ),
    ]
